Repository palantir/foundry-platform-python, pull requests merged in 2025-02, with the labels that each got.

#115 Remove Nulls in Query Param Serialization
  changelog/@unreleased/pr-115.v2.yml
  foundry/_core/api_client.py
Labels: merge when ready, autorelease

#116 Force Include Components for RDP Support
  config.json
Labels: merge when ready

#117 Config Fix
  config.json
Labels: no changelog

#130 Require Pydantic 2.6
  .circleci/config.yml
  changelog/@unreleased/pr-130.v2.yml
  foundry/_versions.py
  foundry/v1/ontologies/errors/__init__.py
  pyproject.toml
  tox.ini
Labels: autorelease

#148 Add SqlQueries
  config.json
Labels: no changelog
